posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForms(Form):
    title = StringField('Title', render_kw={'placeholder': 'Заголовок'})
    body = TextAreaField('Body', render_kw={'placeholder': 'Текст'})

posts/blueprint.py
from flask import Blueprint
from flask import render_template, redirect, request, url_for
from models import Post, Tag
from app import db, user_datastore
from .forms import PostForms


from flask_security import login_required
posts = Blueprint('posts',__name__, template_folder='templates')


@posts.route('/create')
@login_required
def create_post():
	form = PostForms()
	return render_template('posts/create_posts.html', form=form)


@posts.route('/<slug>/edit/', methods=['post','get'])
@login_required
def edit_post(slug):
	post = Post.query.filter(Post.slug==slug).first()
	if request.method=='POST':
		form = PostForms(formdata=request.form, obj=post)
		form.populate_obj(post)
		db.session.commit()
		return redirect(url_for('posts.post_detail', slug=post.slug))

	form = PostForms(obj=post)
	return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def posts_index():
	# p = Post.query.all()
	page = request.args.get('page')
	if page and page.isdigit():
		page = int(page)
	else:
		page = 1

	p = Post.query.order_by(Post.created.desc())#all()
	pages = p.paginate(page=page, per_page=3)

	return render_template('posts/index.html', posts=p, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
	post = Post.query.filter(Post.slug==slug).first()
	print(type(post))
	tags = [] #post.tags
	return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/create', methods=['post', 'get'])
def post_create():
	return render_template('posts/create_posts.html')


@posts.route('/created', methods=['post', 'get'])
def post_created():
	title = request.form.get('title')
	body = request.form.get('body')
	# tag = request.form.get('tag')

	try:
		# t = Tag(name=tag)
		p = Post(title=title, body=body)
		db.session.add(p)
		db.session.commit()
		return redirect(url_for('posts.posts_index'))
	except:
		return r'ошибка базы данных'


@posts.route('/tag/<slug>', methods=['get'])
def tags_detail(slug):
	tag = Tag.query.filter(Tag.slug==slug).first()
	posts = tag.posts.all()
	return render_template('posts/tag_detail.html', posts=posts, tag=tag)


@posts.route('/search', methods=['get', 'post'])
def search():
	search_word = request.form.get('search_word')
	posts = Post.query.filter(Post.title.contains(search_word)|Post.body.contains(search_word)).all()
	amount = len(posts)
	return render_template('posts/search.html', search_word=search_word, posts=posts, anount=amount)


@posts.route('/create_user', methods=['POST','GET'])
def create_user():
	if request.method=='POST':
		email = request.form['email']
		password = request.form['password']
		user_datastore.create_user(email=email, password=password)

		try:
			db.session.commit()
		except:
			return r'ошибка базы данных'

		return redirect(url_for('posts.posts_index'))
	return render_template('posts/create_user.html')

posts/templates/posts/create_posts.html
{% extends 'base.html' %}

{% block title %}
Создание сообщения
{% endblock title %}



{% block content %}
<h1>Новая запись</h1>

<p>
<form action="{{url_for('posts.post_created')}}" method="post">

    {% for fild in form %}
    <p> {{ fild.label }} </p>
    <p> {{ fild }} </p>
    {% endfor %}

    <p>
    <button type="submit">опубликовать</button>
    </p>



</form>

</p>

{% endblock %}

posts/templates/posts/create_user.html
{% extends 'base.html' %}

{% block title %}
Создание пользователя
{% endblock title %}


{% block content %}

<h1>Создать нового пользователя</h1>

<form action="{{url_for('posts.create_user')}}" method="post">
    <input name="email" type="email">
    <input name="password" type="password">
    <button type="submit">create</button>

</form>


{% endblock content %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
Edit Post
{% endblock title %}



{% block content %}
<h1>Список предложений</h1>

<p>
<form action="{{url_for('posts.edit_post', slug=post.slug)}}" method="post">

    {% for fild in form %}
    <p> {{fild.lable}} </p>
    <p> {{fild}} </p>
    {% endfor %}

    <p>
    <button type="submit">обновить</button>
    </p>



</form>

</p>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block search %}
<li class="nav-item">
        <form action="{{url_for('posts.search')}}" method="post">
          <input type="text"  placeholder="search" name="search_word" value="{{request.args.get('search_word','')}}">
            <button type="submit">Поиск</button>
        </form>
</li>
{% endblock %}

{% block title %}
Сообщения
{% endblock title %}



{% block content %}

<h1>Напиши пост товарищь не стой молча в стороне</h1>

<a href="{{url_for('posts.post_create')}}">создать новую запись</a>

    {%for post in pages.items%}
<p>
    <a href="{{url_for('posts.post_detail',slug=post.slug)}}"
            <h1>{{post.id}}, {{post.title}}, {{post.created.strftime('%Y-%m-%d(%H:%M)')}}</h1>
    </a>
</p>
    {%endfor%}


<nav aria-label="...">
  <ul class="pagination">

    <li
        {% if not pages.has_prev %}
            class="page-item disabled"
        {% endif %}
    >
      <a href="./?page={{ pages.prev_num }}" class="page-link">Previous</a>
    </li>

      {% for page in pages.iter_pages(left_edge=2, left_current=2, right_current=2, right_edge=2) %}
      <li {% if page == pages.page %} class="page-item active" aria-current="page" {% endif %}>
          {% if page==None %}
            <a class="page-link" >...</a>
          {% else %}
            <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
          {% endif %}
      </li>
      {% endfor %}


    <li
        {% if not pages.has_next %}
            class="page-item disabled"
        {% endif %}
    >
      <a href="./?page={{ pages.next_num }}" class="page-link">Next</a>
    </li>


  </ul>
</nav>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    <h1> {{post.title}} </h1>
{% endblock title %}

{% block content %}

    <h1>{{post.title}}</h1>

<!--        tags-->
<!--        {% for tag in tags %}-->
<!--        <p>{{tag.name}}</p>-->
<!--        {% endfor %}-->
<br/>
    {{post.body}}
<p/>
<a href="{{url_for('posts.edit_post', slug=post.slug)}}"> Редактировать</a>


{% endblock %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block title %}
Результат поиска
{% endblock title %}



{% block content %}

<h1>Результат поиска</h1>

<p>Вы хотели найти "{{search_word}}" найдено {{anount}}</p>

{%for post in posts%}
        <a href="{{url_for('posts.post_detail',slug=post.slug)}}"
        <p>{{post.title}}</p>

        <!--      <a href="{{url_for('posts.post_detail',slug=post.slug)}}"-->
        <!--            <h1>{{post.id}}, {{post.title}}, {{post.created}}, {{post.tags}}</h1>-->
        <!--    </a>-->
        </a>
{%endfor%}

{% endblock %}

posts/templates/posts/tag_detail.html
{% extends base.html %}

{% block title %}
{{tag.name}} posts
{% endblock %}